apiVersion: v2
name: opendocman
description: A Helm chart for Kubernetes

type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
  - name: mariadb
    version: 11.0.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - mysql
      - database
      - mariadb
      - bitnami
