#!/bin/bash
# Automatic yearly copyright maintenance
# Generated by copyright-maintenance.sh

cd "/home/logart/Documents/dev/opendocman"
./scripts/copyright-maintenance.sh update-static --force
echo "$(date): Automatic copyright maintenance completed" >> ./logs/copyright-maintenance.log
